/* SPDX-FileCopyrightText: Mistial Dev
 * SPDX-License-Identifier: GPL-2.0-or-later */
#ifndef TINY_CRYPTO_X509_OCSP_H_
#define TINY_CRYPTO_X509_OCSP_H_

#include <tiny_crypto/x509_path.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum { TC_OCSP_GOOD, TC_OCSP_REVOKED, TC_OCSP_UNKNOWN, TC_OCSP_UNAVAILABLE } TC_OCSP_status;

typedef struct {
  TC_OCSP_status status;
  TC_X509_time produced_at, this_update, next_update, revocation_time;
  int has_next_update, has_revocation_time;
} TC_OCSP_result;

typedef struct {
  TC_bytes response;
  TC_bytes certificate;
  TC_bytes expected_nonce;
  /* The issuer name and key must come from the already validated path. */
  const TC_X509_trust_anchor* issuer;
  const TC_X509_store_source* certificates;
  TC_X509_time at;
  size_t max_age_seconds, clock_skew_seconds;
  size_t max_response_bytes, max_responses, max_certificates;
  const TC_TLV_limits* parsing;
  const TC_X509_signature_provider* signatures;
} TC_OCSP_verify_request;

typedef struct {
  TC_TLV_frame* frames;
  size_t frame_capacity;
  TC_bytes* extension_oids;
  size_t extension_capacity;
  TC_X509_name_workspace names;
} TC_OCSP_workspace;

/* Verify a complete DER OCSPResponse, including one received by stapling.
 * Response and certificate bytes remain borrowed and unchanged during the call.
 * The certificate path and issuer must already be trusted by the caller.
 * OK means a status is in out; successful responses are authenticated.
 * An unsuccessful OCSPResponse yields UNAVAILABLE without a signature. Other
 * results leave out unchanged. Work and scratch may change on every result. */
TC_TLV_result TC_OCSP_response_verify(const TC_OCSP_verify_request* request,
                                      const TC_OCSP_workspace* workspace, size_t* work,
                                      TC_OCSP_result* out);

/* Encode one unsigned OCSPRequest into caller storage. A present nonce is
 * generated by the caller and must be 32..128 bytes. SHA-256 is recommended
 * for CertID; pass TC_HASH_SHA1 for a legacy responder. */
TC_TLV_result TC_OCSP_request_encode(TC_bytes certificate, const TC_X509_trust_anchor* issuer,
                                     TC_hash_algorithm hash, TC_bytes nonce,
                                     const TC_TLV_limits* parsing,
                                     const TC_OCSP_workspace* workspace, size_t* work,
                                     TC_buffer encoded, size_t* length);

#ifdef __cplusplus
}
#endif
#endif
