#!/usr/bin/env python3
# SPDX-FileCopyrightText: Mistial Dev
# SPDX-License-Identifier: GPL-2.0-or-later
"""
generate_hash_vectors.py
Generates the checked-in tests/hash/test_vectors.h for tiny-crypto-c.

Covers SHA-1, SHA-224, SHA-256, SHA-384, SHA-512 and their HMACs. Digests come
from the Python standard library (hashlib / hmac) and every value is
cross-checked against the `openssl dgst` command line tool. A mismatch is a
hard failure. Regenerate on demand with `make regenerate-vectors`.
"""

import hashlib
import hmac
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER_PATH = os.path.join(ROOT, "tests", "hash", "test_vectors.h")

# Digest name and output length. SHA-1/SHA-224/SHA-256 use 64-byte blocks
# (pad boundary at 56), SHA-384/SHA-512 use 128-byte blocks (boundary at 112).
ALGORITHMS = [("sha1", 20), ("sha224", 28), ("sha256", 32), ("sha384", 48), ("sha512", 64)]

BOUNDARY_LENGTHS = [0, 1, 55, 56, 57, 63, 64, 65, 111, 112, 113, 119, 120, 127,
                    128, 129, 200, 239, 240, 241, 255, 256]
HMAC_KEY_LENGTHS = [0, 1, 63, 64, 65, 127, 128, 129, 131]

# FIPS 180-4 examples (also NIST SHAVS "Examples with Intermediate Values")
FIPS_MESSAGES = [
    ("empty", b""),
    ("abc", b"abc"),
    ("two_block", b"abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq"),
    ("four_block", b"abcdefghbcdefghicdefghijdefghijkefghijklfghijklmghijklmnhijklmnoijklmnopjklmnopqklmnopqrlmnopqrsmnopqrstnopqrstu"),
]

# RFC 2202 (HMAC-SHA-1) test cases 1-7
RFC2202 = [
    (bytes.fromhex("0b" * 20), b"Hi There"),
    (b"Jefe", b"what do ya want for nothing?"),
    (bytes.fromhex("aa" * 20), bytes.fromhex("dd" * 50)),
    (bytes.fromhex("0102030405060708090a0b0c0d0e0f10111213141516171819"), bytes.fromhex("cd" * 50)),
    (bytes.fromhex("0c" * 20), b"Test With Truncation"),
    (bytes.fromhex("aa" * 80), b"Test Using Larger Than Block-Size Key - Hash Key First"),
    (bytes.fromhex("aa" * 80), b"Test Using Larger Than Block-Size Key and Larger Than One Block-Size Data"),
]

# RFC 4231 (HMAC-SHA-224/256/384/512) test cases 1-7
RFC4231 = [
    (bytes.fromhex("0b" * 20), b"Hi There"),
    (b"Jefe", b"what do ya want for nothing?"),
    (bytes.fromhex("aa" * 20), bytes.fromhex("dd" * 50)),
    (bytes.fromhex("0102030405060708090a0b0c0d0e0f10111213141516171819"), bytes.fromhex("cd" * 50)),
    (bytes.fromhex("0c" * 20), b"Test With Truncation"),
    (bytes.fromhex("aa" * 131), b"Test Using Larger Than Block-Size Key - Hash Key First"),
    (bytes.fromhex("aa" * 131),
     b"This is a test using a larger than block-size key and a larger than block-size data. "
     b"The key needs to be hashed before being used by the HMAC algorithm."),
]


def pattern(length):
    return bytes((i & 0xFF) for i in range(length))


def openssl_digest(algorithm, data):
    result = subprocess.run(
        ["openssl", "dgst", "-" + algorithm, "-binary"],
        input=data, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
    return result.stdout


def openssl_hmac(algorithm, key, data):
    if len(key) == 0:
        # `-macopt hexkey:` rejects an empty key; fall back to hashlib-only for that case.
        return None
    result = subprocess.run(
        ["openssl", "dgst", "-" + algorithm, "-mac", "HMAC", "-macopt", "hexkey:" + key.hex(), "-binary"],
        input=data, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True)
    return result.stdout


def digest(algorithm, data):
    expected = hashlib.new(algorithm, data).digest()
    actual = openssl_digest(algorithm, data)
    if actual != expected:
        raise SystemExit(f"openssl {algorithm} mismatch for {len(data)}-byte message")
    return expected


def mac(algorithm, key, data):
    expected = hmac.new(key, data, algorithm).digest()
    actual = openssl_hmac(algorithm, key, data)
    if actual is not None and actual != expected:
        raise SystemExit(f"openssl hmac-{algorithm} mismatch for {len(key)}-byte key")
    return expected


def c_array(name, data):
    if len(data) == 0:
        return f"static const uint8_t {name}[1] = {{ 0x00 }}; /* empty; length 0 */\n"
    lines = []
    for offset in range(0, len(data), 12):
        chunk = data[offset:offset + 12]
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    body = "\n".join(lines).rstrip(",")
    return f"static const uint8_t {name}[{len(data)}] = {{\n{body}\n}};\n"


def main():
    out = []
    out.append("/*\n * SPDX-FileCopyrightText: Mistial Dev\n * SPDX-License-Identifier: GPL-2.0-or-later\n */\n\n")
    out.append("/* Auto-generated by tools/generate_hash_vectors.py; do not edit. */\n")
    out.append("#ifndef TEST_VECTORS_H\n#define TEST_VECTORS_H\n\n#include <stdint.h>\n#include <stddef.h>\n\n")

    out.append("/* --- FIPS 180-4 examples --- */\n")
    for name, message in FIPS_MESSAGES:
        out.append(c_array(f"fips_{name}_msg", message))
        out.append(f"#define FIPS_{name.upper()}_LEN {len(message)}\n")
        for algorithm, _ in ALGORITHMS:
            out.append(c_array(f"fips_{name}_{algorithm}", digest(algorithm, message)))
        out.append("\n")

    million = b"a" * 1000000
    out.append("/* One million repetitions of 'a' */\n")
    for algorithm, _ in ALGORITHMS:
        out.append(c_array(f"million_a_{algorithm}", digest(algorithm, million)))
    out.append("\n")

    out.append("/* --- Padding boundary lengths over the pattern (i & 0xFF) --- */\n")
    out.append(f"#define BOUNDARY_COUNT {len(BOUNDARY_LENGTHS)}\n")
    out.append("static const size_t boundary_lengths[BOUNDARY_COUNT] = { " +
               ", ".join(str(n) for n in BOUNDARY_LENGTHS) + " };\n")
    for algorithm, size in ALGORITHMS:
        out.append(f"static const uint8_t boundary_{algorithm}[BOUNDARY_COUNT][{size}] = {{\n")
        for n in BOUNDARY_LENGTHS:
            out.append("  { " + ", ".join(f"0x{b:02x}" for b in digest(algorithm, pattern(n))) + " },\n")
        out.append("};\n")
    out.append("\n")

    out.append("/* --- RFC 2202 HMAC-SHA-1 test cases 1-7 --- */\n")
    out.append("struct hmac_vector { const uint8_t* key; size_t key_len; const uint8_t* msg; size_t msg_len; const uint8_t* tag; };\n")
    for index, (key, message) in enumerate(RFC2202, start=1):
        out.append(c_array(f"rfc2202_{index}_key", key))
        out.append(c_array(f"rfc2202_{index}_msg", message))
        out.append(c_array(f"rfc2202_{index}_tag", mac("sha1", key, message)))
    out.append(f"#define RFC2202_COUNT {len(RFC2202)}\n")
    out.append("static const struct hmac_vector rfc2202[RFC2202_COUNT] = {\n")
    for index, (key, message) in enumerate(RFC2202, start=1):
        out.append(f"  {{ rfc2202_{index}_key, {len(key)}, rfc2202_{index}_msg, {len(message)}, rfc2202_{index}_tag }},\n")
    out.append("};\n\n")

    out.append("/* --- RFC 4231 HMAC-SHA-224/256/384/512 test cases 1-7 --- */\n")
    out.append("/* rfc4231[] keeps the SHA-256 tags; the other digests get their own tables. */\n")
    for index, (key, message) in enumerate(RFC4231, start=1):
        out.append(c_array(f"rfc4231_{index}_key", key))
        out.append(c_array(f"rfc4231_{index}_msg", message))
        out.append(c_array(f"rfc4231_{index}_tag", mac("sha256", key, message)))
        for algorithm in ("sha224", "sha384", "sha512"):
            out.append(c_array(f"rfc4231_{index}_tag_{algorithm}", mac(algorithm, key, message)))
    out.append(f"#define RFC4231_COUNT {len(RFC4231)}\n")
    out.append("static const struct hmac_vector rfc4231[RFC4231_COUNT] = {\n")
    for index, (key, message) in enumerate(RFC4231, start=1):
        out.append(f"  {{ rfc4231_{index}_key, {len(key)}, rfc4231_{index}_msg, {len(message)}, rfc4231_{index}_tag }},\n")
    out.append("};\n")
    for algorithm in ("sha224", "sha384", "sha512"):
        out.append(f"static const struct hmac_vector rfc4231_{algorithm}[RFC4231_COUNT] = {{\n")
        for index, (key, message) in enumerate(RFC4231, start=1):
            out.append(f"  {{ rfc4231_{index}_key, {len(key)}, rfc4231_{index}_msg, {len(message)}, rfc4231_{index}_tag_{algorithm} }},\n")
        out.append("};\n")
    out.append("\n")

    out.append("/* --- HMAC key-length cases: key = pattern(k), msg = pattern(37) --- */\n")
    keymsg = pattern(37)
    out.append(c_array("hmac_keylen_msg", keymsg))
    out.append(f"#define HMAC_KEYLEN_COUNT {len(HMAC_KEY_LENGTHS)}\n")
    out.append("static const size_t hmac_key_lengths[HMAC_KEYLEN_COUNT] = { " +
               ", ".join(str(n) for n in HMAC_KEY_LENGTHS) + " };\n")
    for algorithm, size in ALGORITHMS:
        out.append(f"static const uint8_t hmac_keylen_{algorithm}[HMAC_KEYLEN_COUNT][{size}] = {{\n")
        for n in HMAC_KEY_LENGTHS:
            out.append("  { " + ", ".join(f"0x{b:02x}" for b in mac(algorithm, pattern(n), keymsg)) + " },\n")
        out.append("};\n")
    out.append("\n")

    out.append("#endif /* TEST_VECTORS_H */\n")

    with open(HEADER_PATH, "w", newline="\n") as handle:
        handle.write("".join(out))
    print(f"Wrote {HEADER_PATH}")


if __name__ == "__main__":
    try:
        main()
    except FileNotFoundError as error:
        print(f"error: {error} (is the openssl CLI installed?)", file=sys.stderr)
        sys.exit(1)
