#!/usr/bin/env python3
# SPDX-FileCopyrightText: Mistial Dev
# SPDX-License-Identifier: GPL-2.0-or-later
"""
generate_des_vectors.py
Generates NIST / ISO test vectors for DES and 3DES (ECB, CBC, CTR)
using Python cryptography / PyCryptodome for tiny-crypto-c test suite.
"""

import sys
import os

try:
    from cryptography.hazmat.decrepit.ciphers.algorithms import TripleDES
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
    from cryptography.hazmat.backends import default_backend
    HAVE_CRYPTO = True
except ImportError:
    try:
        from Crypto.Cipher import DES, DES3
        HAVE_CRYPTO = True
    except ImportError:
        HAVE_CRYPTO = False

def hex_array(data):
    return ", ".join(f"0x{b:02x}" for b in data)

def ctr_crypt(cipher, iv, data):
    stream = bytearray()
    counter = int.from_bytes(iv, "big")
    while len(stream) < len(data):
        stream.extend(cipher.encryptor().update(counter.to_bytes(8, "big")))
        counter += 1
    return bytes(a ^ b for a, b in zip(data, stream))

def generate_vectors():
    print("Generating DES & 3DES Test Vectors...")

    # Single DES ECB Test Vectors (NIST SP 800-20)
    des_key1 = bytes.fromhex("0123456789ABCDEF")
    des_pt1  = bytes.fromhex("4E6F772069732074") # 'Now is t'
    
    # 2-Key 3DES ECB Test Vectors
    tdes_key2 = bytes.fromhex("0123456789ABCDEF23456789ABCDEF01")
    tdes_pt2  = bytes.fromhex("6BC1BEE22E409F96E93D7E117393172A") # 16 bytes
    
    # 3-Key 3DES ECB Test Vectors
    tdes_key3 = bytes.fromhex("0123456789ABCDEF23456789ABCDEF01456789ABCDEF0123")
    tdes_pt3  = bytes.fromhex("4E6F77206973207468652074696D6520") # 16 bytes

    # CBC IV
    iv_cbc = bytes.fromhex("1234567890ABCDEF")

    # CTR IV
    iv_ctr = bytes.fromhex("F0F1F2F3F4F5F6F7")
    ctr_pt = bytes(range(13))

    # Compute ciphertexts using cryptography / TripleDES
    backend = default_backend()

    # 1. Single DES ECB (via 3DES key1*3)
    c_des_ecb = Cipher(TripleDES(des_key1 * 3), modes.ECB(), backend=backend)
    des_ecb_ct = c_des_ecb.encryptor().update(des_pt1)

    # 2. Single DES CBC
    c_des_cbc = Cipher(TripleDES(des_key1 * 3), modes.CBC(iv_cbc), backend=backend)
    des_cbc_ct = c_des_cbc.encryptor().update(des_pt1)

    # 3. 2-Key 3DES ECB (key2 = K1 + K2 + K1)
    key16_exp = tdes_key2[:16] + tdes_key2[:8]
    c_2k_ecb = Cipher(TripleDES(key16_exp), modes.ECB(), backend=backend)
    tdes_2k_ecb_ct = c_2k_ecb.encryptor().update(tdes_pt2)

    # 4. 2-Key 3DES CBC
    c_2k_cbc = Cipher(TripleDES(key16_exp), modes.CBC(iv_cbc), backend=backend)
    tdes_2k_cbc_ct = c_2k_cbc.encryptor().update(tdes_pt2)

    # 5. 3-Key 3DES ECB
    c_3k_ecb = Cipher(TripleDES(tdes_key3), modes.ECB(), backend=backend)
    tdes_3k_ecb_ct = c_3k_ecb.encryptor().update(tdes_pt3)

    # 6. 3-Key 3DES CBC
    c_3k_cbc = Cipher(TripleDES(tdes_key3), modes.CBC(iv_cbc), backend=backend)
    tdes_3k_cbc_ct = c_3k_cbc.encryptor().update(tdes_pt3)

    # 7. Single DES OFB / CFB64 / CFB8 (via 3DES key1*3)
    des_ofb_ct = Cipher(TripleDES(des_key1 * 3), modes.OFB(iv_cbc), backend=backend).encryptor().update(des_pt1)
    des_cfb64_ct = Cipher(TripleDES(des_key1 * 3), modes.CFB(iv_cbc), backend=backend).encryptor().update(des_pt1)
    des_cfb8_ct = Cipher(TripleDES(des_key1 * 3), modes.CFB8(iv_cbc), backend=backend).encryptor().update(des_pt1)

    # 8. 3-Key 3DES OFB / CFB64 / CFB8
    tdes_3k_ofb_ct = Cipher(TripleDES(tdes_key3), modes.OFB(iv_cbc), backend=backend).encryptor().update(tdes_pt3)
    tdes_3k_cfb64_ct = Cipher(TripleDES(tdes_key3), modes.CFB(iv_cbc), backend=backend).encryptor().update(tdes_pt3)
    tdes_3k_cfb8_ct = Cipher(TripleDES(tdes_key3), modes.CFB8(iv_cbc), backend=backend).encryptor().update(tdes_pt3)

    # 9. CTR uses the big-endian 64-bit IV as the initial counter.
    des_ctr_ct = ctr_crypt(Cipher(TripleDES(des_key1 * 3), modes.ECB(), backend=backend), iv_ctr, ctr_pt)
    tdes3_ctr_ct = ctr_crypt(Cipher(TripleDES(tdes_key3), modes.ECB(), backend=backend), iv_ctr, ctr_pt)

    print("Single DES ECB CT:", des_ecb_ct.hex().upper())
    print("Single DES CBC CT:", des_cbc_ct.hex().upper())
    print("2-Key 3DES ECB CT:", tdes_2k_ecb_ct.hex().upper())
    print("2-Key 3DES CBC CT:", tdes_2k_cbc_ct.hex().upper())
    print("3-Key 3DES ECB CT:", tdes_3k_ecb_ct.hex().upper())
    print("3-Key 3DES CBC CT:", tdes_3k_cbc_ct.hex().upper())

    # Write test_vectors.h header
    header_content = f"""/* SPDX-FileCopyrightText: Mistial Dev
 * SPDX-License-Identifier: GPL-2.0-or-later */
/* Auto-generated by tools/generate_des_vectors.py; do not edit. */
#ifndef TEST_VECTORS_H
#define TEST_VECTORS_H

#include <stdint.h>

/* Single DES Test Vector (ECB) */
static const uint8_t des_test_key[8] = {{ {hex_array(des_key1)} }};
static const uint8_t des_test_pt[8]  = {{ {hex_array(des_pt1)} }};
static const uint8_t des_test_ct[8]  = {{ {hex_array(des_ecb_ct)} }};

/* Single DES Test Vector (CBC) */
static const uint8_t des_cbc_iv[8]   = {{ {hex_array(iv_cbc)} }};
static const uint8_t des_cbc_ct[8]   = {{ {hex_array(des_cbc_ct)} }};

/* 2-Key 3DES Test Vectors */
static const uint8_t tdes2_key[16]    = {{ {hex_array(tdes_key2)} }};
static const uint8_t tdes2_pt[16]     = {{ {hex_array(tdes_pt2)} }};
static const uint8_t tdes2_ecb_ct[16] = {{ {hex_array(tdes_2k_ecb_ct)} }};
static const uint8_t tdes2_cbc_ct[16] = {{ {hex_array(tdes_2k_cbc_ct)} }};

/* 3-Key 3DES Test Vectors */
static const uint8_t tdes3_key[24]    = {{ {hex_array(tdes_key3)} }};
static const uint8_t tdes3_pt[16]     = {{ {hex_array(tdes_pt3)} }};
static const uint8_t tdes3_ecb_ct[16] = {{ {hex_array(tdes_3k_ecb_ct)} }};
static const uint8_t tdes3_cbc_ct[16] = {{ {hex_array(tdes_3k_cbc_ct)} }};

/* CTR Mode IV */
static const uint8_t des_ctr_iv[8]    = {{ {hex_array(iv_ctr)} }};
static const uint8_t des_ctr_pt[13]   = {{ {hex_array(ctr_pt)} }};
static const uint8_t des_ctr_ct[13]   = {{ {hex_array(des_ctr_ct)} }};
static const uint8_t tdes3_ctr_ct[13] = {{ {hex_array(tdes3_ctr_ct)} }};

/* Single DES OFB / CFB Test Vectors (IV = des_cbc_iv) */
static const uint8_t des_ofb_ct[8]    = {{ {hex_array(des_ofb_ct)} }};
static const uint8_t des_cfb64_ct[8]  = {{ {hex_array(des_cfb64_ct)} }};
static const uint8_t des_cfb8_ct[8]   = {{ {hex_array(des_cfb8_ct)} }};

/* 3-Key 3DES OFB / CFB Test Vectors (IV = des_cbc_iv) */
static const uint8_t tdes3_ofb_ct[16]   = {{ {hex_array(tdes_3k_ofb_ct)} }};
static const uint8_t tdes3_cfb64_ct[16] = {{ {hex_array(tdes_3k_cfb64_ct)} }};
static const uint8_t tdes3_cfb8_ct[16]  = {{ {hex_array(tdes_3k_cfb8_ct)} }};

#endif /* TEST_VECTORS_H */
"""
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    header_path = os.path.join(repo_root, "tests", "des", "test_vectors.h")
    with open(header_path, "w") as f:
        f.write(header_content)
    print(f"Generated {header_path}")

if __name__ == "__main__":
    generate_vectors()
