# SPDX-FileCopyrightText: Mistial Dev
# SPDX-License-Identifier: GPL-2.0-or-later
"""Synthetic PIV SM sessions with scalar 1 on both sides and host ID zero."""
import hashlib
from pki_fixtures import cvc, tlv, c_array

# SEC 2 generators. Tags were computed independently with Python cryptography.
ANSWERS = {
    256: (
        "046b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296"
        "4fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5",
        "aee83deaa036122a528b590ca31d6acf", "79e37a04a87d44f77f6c5cd3649859b7",
        "0e3278169442f46145476279afd5421c"),
    384: (
        "04aa87ca22be8b05378eb1c71ef320ad746e1d3b628ba79b9859f741e082542a385502f25dbf55296c3a545e3872760ab7"
        "3617de4a96262c6f5d9e98bf9292dc29f8f41dbd289a147ce9da3113b5f0b8c00a60b1ce1d7e819d7a431d7c90ea0e5f",
        "a567d63b1a99abf7d22dc4dec7496799", "7242f9e39f3aebb94235ebe991abbcf8",
        "aa4fa6963ffe2816c205b31aa53da0a1"),
}

# Independently calculated with Python cryptography from the synthetic chain.
CHAIN_ANSWERS = {
    256: ("a5a88d5e7837ae5c3a62f7a5c9d5f89b",
          "d6e25548917e4e320f09c88788bd772e",
          "604cd21f8f12673b1831a05b25fb54a1"),
    384: ("a0e6266796593761ec6eda13bc4190bb",
          "2b70345df47da4782af482143425ed79",
          "656a7a1cc77b8e8d856d9ff8b19973b2"),
}


def _session(bits, certificate, confirmation, command_mac, response_mac, intermediate=b""):
    public = bytes.fromhex(ANSWERS[bits][0])
    width = bits // 8
    key_length = 16 if bits == 256 else 32
    suite = 0x27 if bits == 256 else 0x2e
    nonce = bytes(range(16 if bits == 256 else 24))
    card_id = hashlib.sha256(certificate).digest()[:8]
    other = (bytes([4] + [9 if bits == 256 else 13] * 4 + [8]) + bytes(8) +
             bytes.fromhex("010010") + public[1:17] + bytes([8]) + card_id +
             bytes([len(nonce)]) + nonce + bytes.fromhex("0100"))
    digest = hashlib.sha256 if bits == 256 else hashlib.sha384
    material = b"".join(digest(i.to_bytes(4, "big") + public[1:1 + width] + other).digest()
                        for i in range(1, 4))[:4 * key_length]
    body = tlv(0x7c, tlv(0x81, bytes(9) + public) + tlv(0x82, b""))
    return {
        "public_key": public,
        "request": bytes([0, 0x87, suite, 4, len(body)]) + body + b"\0",
        "response": tlv(0x7c, tlv(0x82, b"\0" + nonce + confirmation + certificate)),
        "material": material,
        "command": tlv(0x8e, command_mac[:8]),
        "reply": tlv(0x99, bytes.fromhex("9000")) + tlv(0x8e, response_mac[:8]),
        "intermediate": intermediate,
    }


def session(bits):
    public, confirmation, command_mac, response_mac = map(bytes.fromhex, ANSWERS[bits])
    return _session(bits, cvc(bits, public), confirmation, command_mac, response_mac)


def chain_session(bits):
    public = bytes.fromhex(ANSWERS[bits][0])
    subject = hashlib.sha1(public).digest()[:8]
    intermediate = cvc(bits, public, subject=subject, role=0x12)
    certificate = cvc(bits, public, issuer=subject)
    confirmation, command_mac, response_mac = map(bytes.fromhex, CHAIN_ANSWERS[bits])
    return _session(bits, certificate, confirmation, command_mac, response_mac, intermediate)


if __name__ == "__main__":
    import argparse
    from pathlib import Path
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    fields = ("public_key", "request", "response", "material", "command", "reply", "intermediate")
    lines = ["/* Generated by tools/sm_fixtures.py. */", "#include <tiny_crypto/piv_sm.h>"]
    for bits in (256, 384):
        for name, value in session(bits).items():
            if value:
                lines.append("static " + c_array(value, f"sm_{bits}_{name}"))
        for name, value in chain_session(bits).items():
            lines.append("static " + c_array(value, f"sm_{bits}_chain_{name}"))
    lines.append("struct tc_sm_fixture { TC_PIV_SM_suite suite; " +
                 " ".join(f"TC_bytes {name};" for name in fields) + " };")
    lines.append("static const struct tc_sm_fixture sm_fixtures[] = {")
    for bits in (256, 384):
        suite = "TC_PIV_SM_CS2" if bits == 256 else "TC_PIV_SM_CS7"
        lines.append("{" + suite + "," + ",".join(
            "{NULL,0}" if name == "intermediate" else
            f"{{sm_{bits}_{name},sizeof sm_{bits}_{name}}}" for name in fields) + "},")
        lines.append("{" + suite + "," + ",".join(
            f"{{sm_{bits}_chain_{name},sizeof sm_{bits}_chain_{name}}}" for name in fields) + "},")
    lines.append("};")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n")
